### ISSUE TITLE
When someone writes too many characters, the text breaks and invades the keyboard

### ISSUE THREAD

**Issue by Gabriel-Aroucas** [accesibleprogramacion/calculadora#2]
The solution for this problem is very simple

```css

.display {
    grid-column: 1 / -1;
    padding: 16px;
    display: flex;
    margin: 10px 10px 20px;
    flex-direction: column;
    align-items: flex-end;
    background-color: #363636;
    border-radius: 32px;
    text-align: right;
    justify-content: space-between;
    word-break: break-all;
    overflow: scroll;  // ***here***
    box-shadow: 0px 0px 0px 10px #00000033;
}

```

I liked your solution !
